version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "passw@rd@,123W.!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
